#!/usr/bin/python3
"""
Fabric script that generates a .tgz archive from the contents
of the web_static folder of your AirBnB Clone repo.
"""
from fabric.api import local
from datetime import datetime
import os

def do_pack():
    """Generates a .tgz archive from web_static folder."""
    try:
        # Create the 'versions' folder if it doesn't exist
        local("mkdir -p versions")

        # Generate the archive filename
        now = datetime.utcnow()
        archive_name = "web_static_{}{}{}{}{}{}.tgz".format(
            now.year, now.month, now.day, now.hour, now.minute, now.second)

        # Compress the web_static folder into the archive
        local("tar -cvzf versions/{} web_static".format(archive_name))

        # Return the archive path if generated successfully
        return os.path.join("versions", archive_name)
    except Exception as e:
        print(e)
        return None

if __name__ == "__main__":
    do_pack()
